- name: Run PMD
  uses: pmd/pmd-github-action@v2
  with:
    version: '7.0.0'
    sourcePath: 'force-app/main/default'
    rulesets: 'config/pmd/apex-ruleset.xml'
    analyzeModifiedFilesOnly: false
    uploadSarifReport: true
    createGitHubAnnotations: true
